name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: | 
        docker login u matiasmartineeez -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        docker build . --file Dockerfile --tag matiasmartineeez/venues-and-clients-manager-api
        docker push matiasmartineeez/venues-and-clients-manager-api
        
